### ISSUE TITLE
hitting unknown exception when trying to create a hippo app

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#780] opened 2022-05-17 21:17 UTC
I am unable to get a 200 when I try to create a hippo app using the following command. I get a 500 but when I check the dashboard, the app exists.
```
examples/http-rust [main] $ hippo app add spin-hello-world spin-hello-world
Error: {"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occurred while processing your request.","status":500}
```
When I run the command again, I get a validation error that says the specified name already exists.

**Comment by bacongobbler** [comment] 2022-05-17 21:31
Yeah, this is a duplicate of #773. Working on updating the nomad-local-demo as well as the documentation to help accommodate these changes.

**Closed by bacongobbler** 2022-05-17 21:31 UTC
