### ISSUE TITLE
bootstrapping an account

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#805] opened 2022-05-23 19:58 UTC
If I deploy Hippo at the moment in insecure mode, anyone can register an account and then use the account to deploy an app. It would be nice if there was some minimal dance where an account is registered when the hippo server is started and then no other user/account can create additional accounts except the initial account. And if only one account is needed, then the one registered at start time can be used to log in and deploy.

** This feature request / discussion is coming from an idea @lann had in a convo we (@vdice, @radu-matei , @fibonacci1729, @lann) had earlier around the Hippo/Nomad quickstart guide @vdice is working on.

**Comment by bacongobbler** [comment] 2022-05-24 02:25
I’m going to close this as a duplicate of https://github.com/deislabs/hippo/issues/546 because we identified this as one of many potential scenarios. Thanks @michelleN!

**Closed by bacongobbler** 2022-05-24 02:25 UTC
